import type { Tool, ToolResult } from "./types";

export const extractKnowledgeTripletsTool: Tool = {
	name: "extract_knowledge_triplets",
	description: "Parses a valid JSON-array generated by the Ontologist containing [[Subject], [Predicate], [Object]] relationships and structurally formats and saves them into the persistent local Knowledge Graph.",
	parameters: [
		{ name: "triplets", type: "string", description: "Stringified JSON array of objects, e.g. [{\"subject\": \"Machine Learning\", \"predicate\": \"requires\", \"object\": \"Backpropagation\"}]", required: true }
	],
	async execute(args, ctx): Promise<ToolResult> {
		if (!ctx.graphStore) {
			return { success: false, output: "GraphStore is not initialized." };
		}
		
		try {
			const jsonStr = String(args["triplets"]);
			const array = JSON.parse(jsonStr);

			if (!Array.isArray(array)) {
				return { success: false, output: "Passed triplets must be a JSON array of objects." };
			}

			let addedCount = 0;
			for (const item of array) {
				if (item.subject && item.predicate && item.object) {
					ctx.graphStore.addTriplet(String(item.subject), String(item.predicate), String(item.object));
					addedCount++;
				}
			}

			if (addedCount > 0) {
				await ctx.graphStore.save();
				return { success: true, output: `Successfully extracted and appended ${addedCount} logical triplets into the global GraphRAG store.` };
			} else {
				return { success: false, output: "No valid {subject, predicate, object} structures found inside JSON array." };
			}
		} catch (e) {
			return { success: false, output: `JSON Parsing Failed. Ensure you only output raw valid JSON string arrays without markdown code blocks. Error: ${e}` };
		}
	}
};

export const graphTraversalSearchTool: Tool = {
	name: "graph_traversal_search",
	description: "Executes a multi-hop reasoning search traversing explicitly defined GraphRAG dependencies. Use this when simple keyword 'search_vault' fails to trace exact explicit paths between complex abstract entities.",
	parameters: [
		{ name: "entry_entity", type: "string", description: "The exact name of the concept or note you wish to trace outward from.", required: true },
		{ name: "max_depth", type: "number", description: "The number of topological hops to traverse (default 2, max 4).", required: false }
	],
	async execute(args, ctx): Promise<ToolResult> {
		if (!ctx.graphStore) {
			return { success: false, output: "GraphStore is not initialized." };
		}

		const entry = String(args["entry_entity"]);
		const depth = Math.min(Number(args["max_depth"]) || 2, 4);

		if (!entry) return { success: false, output: "entry_entity required." };

		const chains = ctx.graphStore.traverse(entry, depth);

		if (chains.length === 0) {
			return { success: true, output: `The GraphStore found 0 explicit connections radiating from the entity node [${entry}]. Try standard search_vault or check your entity name.` };
		}

		return { 
			success: true, 
			output: `Multi-hop Entity Linkages found starting from [${entry}]:\n` + chains.join("\n") 
		};
	}
};

export function registerGraphTools(registry: import("./registry").ToolRegistry): void {
	registry.register(extractKnowledgeTripletsTool);
	registry.register(graphTraversalSearchTool);
}
